In [1]:
import numpy as np
import pandas as pd

In [2]:
df_uut = pd.read_csv('./datasets/awosdata-21-22-CS Aero.csv',sep=None, engine='python')
df_uut

            Time (UTC)  AT_A  RH_A  QFE1Ma  WS10Ma_A  WD10Ma_A
0     21/04/2026 03:00  29.1    76  1009.5       7.5       299
1     21/04/2026 03:00  29.1    78  1009.5       7.5       299
2     21/04/2026 03:00  29.2    78  1009.5       7.5       300
3     21/04/2026 03:00  29.2    77  1009.5       7.5       300
4     21/04/2026 03:00  29.3    76  1009.5       7.5       300
...                ...   ...   ...     ...       ...       ...
7556  21/04/2026 23:59  27.1    88  1010.0       2.6       166
7557  21/04/2026 23:59  27.1    89  1010.0       2.6       167
7558  21/04/2026 23:59  27.2    91  1010.0       2.6       167
7559  21/04/2026 23:59  27.2    89  1010.0       2.7       168
7560  22/04/2026 00:00  27.2    87  1010.0       2.7       169

[7561 rows x 6 columns]

In [3]:
df_uut['Time (UTC)'] = pd.to_datetime(df_uut['Time (UTC)'])

C:\Users\kalibrasi-jaya\AppData\Local\Temp\ipykernel_21296\658291033.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_uut['Time (UTC)'] = pd.to_datetime(df_uut['Time (UTC)'])

In [4]:
df_uut.rename(columns={'Time (UTC)':'Timestamp'},inplace=True)
df_uut.head()

            Timestamp  AT_A  RH_A  QFE1Ma  WS10Ma_A  WD10Ma_A
0 2026-04-21 03:00:00  29.1    76  1009.5       7.5       299
1 2026-04-21 03:00:00  29.1    78  1009.5       7.5       299
2 2026-04-21 03:00:00  29.2    78  1009.5       7.5       300
3 2026-04-21 03:00:00  29.2    77  1009.5       7.5       300
4 2026-04-21 03:00:00  29.3    76  1009.5       7.5       300

In [5]:
df_uut_resampled = df_uut.set_index("Timestamp").resample("1min").mean().reset_index()
df_uut_resampled.head()

            Timestamp       AT_A       RH_A  QFE1Ma  WS10Ma_A    WD10Ma_A
0 2026-04-21 03:00:00  29.183333  77.000000  1009.5  7.516667  299.666667
1 2026-04-21 03:01:00  29.200000  76.833333  1009.5  7.766667  300.000000
2 2026-04-21 03:02:00  29.300000  78.500000  1009.5  7.833333  300.833333
3 2026-04-21 03:03:00  29.383333  75.166667  1009.5  7.966667  302.333333
4 2026-04-21 03:04:00  29.350000  76.000000  1009.5  8.116667  302.833333

In [6]:
df_uut_resampled.to_csv('data-awos-resamples.csv',index=False)